# Generated by Django 3.2 on 2021-05-30 19:32

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cell',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('count', models.IntegerField()),
                ('create_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('formula_V', models.CharField(max_length=50)),
                ('formula_P', models.CharField(max_length=50)),
                ('parameters_V', models.CharField(max_length=50)),
                ('parameters_P', models.CharField(max_length=50)),
                ('photo', models.ImageField(default='form/default.png', upload_to='form/%Y/%m/%d/')),
            ],
        ),
        migrations.CreateModel(
            name='Research',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('area_name', models.CharField(max_length=200)),
                ('area', models.JSONField(blank=True, null=True)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-create_time'],
            },
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('coords', models.JSONField()),
                ('depth', models.FloatField()),
                ('date', models.DateTimeField()),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('research', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stations', to='research_base.research')),
            ],
        ),
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('horizont', models.FloatField()),
                ('time', models.DateTimeField()),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='samples', to='research_base.station')),
            ],
        ),
        migrations.CreateModel(
            name='Cell_params',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('value', models.FloatField()),
                ('formula', models.CharField(choices=[('V', 'Volume'), ('P', 'Perimeter')], default='V', max_length=1)),
                ('cell', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parameters', to='research_base.cell')),
            ],
        ),
        migrations.AddField(
            model_name='cell',
            name='form',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cells', to='research_base.form'),
        ),
        migrations.AddField(
            model_name='cell',
            name='sample',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cells', to='research_base.sample'),
        ),
        migrations.AddField(
            model_name='cell',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cells', to='research_base.type'),
        ),
    ]
