# Generated by Django 3.2 on 2021-05-28 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research_base', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='research',
            options={'ordering': ['-create_time']},
        ),
        migrations.AddField(
            model_name='cell_params',
            name='formula',
            field=models.CharField(choices=[('V', 'Volume'), ('P', 'Perimeter')], default='V', max_length=1),
        ),
    ]
